### ISSUE TITLE
Stacked area plot would be more appropriate for the downloads trend

### ISSUE THREAD

**Issue by dtolnay** [apskhem/cratesinquire#1]
<table><tr><td>
<img src="https://user-images.githubusercontent.com/1940490/145866455-87c94afb-a530-4fb8-ad86-b9da3042e6bb.png">
</td><td>
<img src="https://user-images.githubusercontent.com/1940490/145866463-555a6230-b063-44a6-b9b0-5f72ae473acb.png">
</td></tr></table>

Notice how the unstacked plot makes it appear incorrectly as though downloads are trending down.

**Comment by apskhem** [comment]
The stack graph was implemented in the new build. Thanks for pointing out the problem.
<img width="916" alt="Screen Shot 2021-12-15 at 02 56 33" src="https://user-images.githubusercontent.com/38898766/146070589-789b43ed-1aa2-4b5f-9633-30d42c0bfc57.png">
