### ISSUE TITLE
Feature Request: Dark mode support

### ISSUE THREAD

**Issue by andrew-ares** [apskhem/cratesinquire#10]
Any plans on that?

**Comment by apskhem** [comment]
I added a dark theme to the web, but it doesn't have an explicit button to turn on or off. This will detect automatically by your browser. For example, this image was taken on my mobile phone with dark mode Chrome.

![3244](https://user-images.githubusercontent.com/38898766/146305316-64c072cb-401c-4fd4-92b8-3c747157efb1.jpg)
