### ISSUE TITLE
Interpolation of downloads goes negative and backwards in time

### ISSUE THREAD

**Issue by dtolnay** [apskhem/cratesinquire#2]
In this graph the teal curve appears to backwards in time (around november 8 and december 4) and negative (november 21).

<br>

![Screenshot from 2021-12-13 10-22-29](https://user-images.githubusercontent.com/1940490/145867174-bc6c47d0-53d8-42ca-ace9-aea1f7fbe4e4.png)

**Comment by apskhem** [comment]
This is because I chose to use Cardinal spline. I changed it to be Catmull–Rom spline. I wish that it could be well-performed.

**Comment by dtolnay** [comment]
Thanks, this looks decent now:

<br>

![Screenshot from 2021-12-14 12-56-34](https://user-images.githubusercontent.com/1940490/146078083-8682a08e-a7f8-4589-9b9c-c5fc9a90a957.png)
