### ISSUE TITLE
Dependency tree is misleading about the total number of crates

### ISSUE THREAD

**Issue by dtolnay** [apskhem/cratesinquire#3]
The following looks like an enormous dependency graph, but in reality it's just repeating the same few dependencies *many* times (winapi, serde, syn, quote, proc-macro2, ...). For example I count 9 different copies of proc-macro2 1.0 in this graph. In reality Cargo would only build that dependency a single time, and it would be nice if the view would capture that.

In particular it looks like this view is associating dependency specs (`^0.1` vs `^0.1.3` etc) with nodes, whereas it would make more sense to me to associate them with edges. Multiple crates can depend on the same dependency with different specifications, and there should only be one node for the dependency for every semver-compatible group of those specifications.

<br>

![Screenshot from 2021-12-13 10-25-47](https://user-images.githubusercontent.com/1940490/145867676-62e1ff92-a2e3-41cb-aea6-8edb49db7c13.png)

**Comment by apskhem** [comment]
I implemented a new look of dependency chart in a form of a directed graph. It will be very messy if the crate has a large dependency. I tried my best to visualize the dependency distance by the scale of color.

![screencapture-localhost-3000-crates-cargo-tally-2022-01-01-01_40_06](https://user-images.githubusercontent.com/38898766/148505134-3e34ec7f-3631-46d4-9edf-fa77cb96e41f.png)
