### ISSUE TITLE
Inability to copy crate version (or anything)

### ISSUE THREAD

**Issue by pacak** [apskhem/cratesinquire#8]
Same problem as with crates.io

https://github.com/rust-lang/crates.io/issues/3952

**Comment by apskhem** [comment]
I added cursor selection to the text box. So, you can copy the text via your context menu or keyboard shortcut. I'm not sure that this will work out for you.

<img width="935" alt="Screen Shot 2021-12-16 at 17 07 12" src="https://user-images.githubusercontent.com/38898766/146351705-484c4b9a-6f6d-4e87-a689-e0efb9bc5270.png">

**Comment by pacak** [comment]
This works great, thank you!
