### ISSUE TITLE
Feature Request: Collapse the info of crate when it has too many versions

### ISSUE THREAD

**Issue by andrew-ares** [apskhem/cratesinquire#9]
Take tokio as an example

![image](https://user-images.githubusercontent.com/40336192/145951964-e971a229-64c3-435f-a30e-212e1a181b74.png)
It may be more ergonomic for users if we do this.

Great website! Thank you

**Comment by apskhem** [comment]
I added collapsable container. If the crate has more than 20 versions, it will show only 20 versions and the rest you have to expand them.

<img width="941" alt="Screen Shot 2021-12-16 at 10 49 07" src="https://user-images.githubusercontent.com/38898766/146304953-a4e693be-d4f7-47da-bcd1-f148f5d7fdee.png">
